databases:
  - name: bank-api-db
    databaseName: bankapi
    user: bankapi
    plan: free

services:
  - type: web
    name: bank-api
    runtime: docker
    plan: free
    region: oregon
    autoDeploy: true
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_RAW_URL
        fromDatabase:
          name: bank-api-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: bank-api-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: bank-api-db
          property: password
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: JAVA_TOOL_OPTIONS
        value: -XX:MaxRAMPercentage=75 -XX:+ExitOnOutOfMemoryError
