server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bankapi}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:bankapi}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

spring.thymeleaf.cache=true
spring.h2.console.enabled=false

server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax

